name: 💬 Developer Feedback
description: Provide feedback on the developer API, integration experience, or documentation
title: '[Feedback]: '
labels: ['feedback', 'dev-ex']
assignees: ['troychaplin']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for testing Block Accessibility Checks! Your feedback helps us improve the plugin and developer experience.

    - type: dropdown
      id: feedback-category
      attributes:
          label: Feedback Category
          description: What aspect would you like to provide feedback on?
          options:
              - Developer API Experience
              - Integration Process
              - Documentation Quality
              - Code Examples
              - JavaScript Validation System
              - PHP Hook System
              - Settings Integration
              - Performance
              - Overall Developer Experience
              - Other
      validations:
          required: true

    - type: textarea
      id: your-experience
      attributes:
          label: Your Experience
          description: What worked well? What was challenging?
          placeholder: |
              Share what you liked and what could be improved.
              - What was intuitive or helpful?
              - What was confusing or difficult?
      validations:
          required: true

    - type: textarea
      id: additional-comments
      attributes:
          label: Additional Comments (optional)
          description: Anything else you'd like to share?
          placeholder: Suggestions, feature requests, or other thoughts...

    - type: dropdown
      id: documentation-rating
      attributes:
          label: Documentation Rating (optional)
          description: How would you rate the documentation?
          options:
              - Excellent
              - Good
              - Average
              - Poor
              - Very Poor

    - type: dropdown
      id: api-ease-of-use
      attributes:
          label: API Ease of Use (optional)
          description: How easy was the developer API to use?
          options:
              - Very Easy
              - Easy
              - Moderate
              - Difficult
              - Very Difficult

    - type: textarea
      id: environment-details
      attributes:
          label: Development Environment (optional)
          description: Details about your development setup
          placeholder: WordPress version, PHP version, build tools, etc.
