name: 📚 Documentation Improvement
description: Suggest improvements to documentation, examples, or guides
title: '[Docs]: '
labels: ['documentation', 'enhancement']
assignees: []
body:
    - type: markdown
      attributes:
          value: |
              Help us improve the documentation! Please select the relevant file and describe the issue or suggestion. Most fields are optional for a quick submission.

    - type: dropdown
      id: doc-type
      attributes:
          label: Documentation Type
          options:
              - Developer API Documentation
              - Integration Examples
              - README File
              - Setup/Installation Guide
              - Troubleshooting Guide
              - Best Practices Guide
              - Plugin Settings Help
              - Other
      validations:
          required: true

    - type: dropdown
      id: doc-location
      attributes:
          label: Document/File Location
          options:
              - README.md
              - docs/developer-api.md
              - docs/quick-start.md
              - docs/api-reference.md
              - docs/features.md
              - docs/troubleshooting.md
              - docs/external-integration.md
              - docs/examples.md
              - docs/advanced.md
              - docs/hooks.md
              - docs/js-integration.md
              - docs/php-integration.md
              - Other
          description: Where is the documentation that needs improvement?
      validations:
          required: true

    - type: dropdown
      id: issue-type
      attributes:
          label: Type of Issue
          options:
              - Missing Information
              - Incorrect Information
              - Unclear Explanation
              - Outdated Content
              - Missing Examples
              - Poor Code Examples
              - Confusing Structure
              - Typos/Grammar
              - Needs More Detail
              - Other
      validations:
          required: true

    - type: textarea
      id: current-problem
      attributes:
          label: Current Problem
          description: What's unclear, missing, or incorrect?
          placeholder: Describe the issue...
      validations:
          required: true

    - type: textarea
      id: suggested-improvement
      attributes:
          label: Suggested Improvement
          description: How would you improve it?
          placeholder: Suggest changes, examples, or clarifications...
      validations:
          required: true

    - type: dropdown
      id: target-audience
      attributes:
          label: Target Audience (optional)
          options:
              - Beginner WordPress Developers
              - Experienced WordPress Developers
              - Block Developers
              - Plugin Developers
              - Theme Developers
              - Non-technical Users
              - All Users
              - Accessibility Specialists

    - type: textarea
      id: use-case
      attributes:
          label: Use Case/Context (optional)
          description: Describe the situation where you encountered this documentation issue
          placeholder: What were you trying to accomplish?

    - type: textarea
      id: example-content
      attributes:
          label: Example Content (optional)
          description: Provide draft text, code, or examples
          render: markdown

    - type: checkboxes
      id: improvement-type
      attributes:
          label: Improvement Type (optional)
          options:
              - label: More detailed explanations
              - label: Additional code examples
              - label: Step-by-step tutorials
              - label: Real-world use cases
              - label: Troubleshooting section
              - label: Visual aids (diagrams, screenshots)
              - label: Links to related resources
              - label: Better organization/structure
              - label: Search/navigation improvements
              - label: FAQ section

    - type: dropdown
      id: complexity-level
      attributes:
          label: Content Complexity (optional)
          options:
              - Basic - High-level overview with simple examples
              - Intermediate - Balanced detail with practical examples
              - Advanced - Comprehensive detail with complex examples
              - Multiple Levels - Different sections for different skill levels

    - type: textarea
      id: related-docs
      attributes:
          label: Related Documentation (optional)
          description: Are there other documents or sections that relate to this issue?

    - type: textarea
      id: research-attempted
      attributes:
          label: Research Attempted (optional)
          description: What did you try to find the information you needed?

    - type: checkboxes
      id: contribution-interest
      attributes:
          label: Contribution Interest (optional)
          options:
              - label: I'd be willing to write a draft of the improved content
              - label: I'd be happy to review proposed changes
              - label: I can provide additional examples or use cases
              - label: I'd like to test documentation improvements
              - label: I'm interested in ongoing documentation contributions

    # Priority Level and Impact Description removed to simplify and avoid expectation setting

    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context (optional)
          description: Any other relevant information or suggestions
