name: 📚 Documentation Improvement
description: Suggest improvements to documentation, examples, or guides
title: '[Docs]: '
labels: ['documentation', 'enhancement']
assignees: []
body:
    - type: markdown
      attributes:
          value: |
              Help us improve the documentation! Please select the relevant file and describe the issue or suggestion. Most fields are optional for a quick submission.

    - type: dropdown
      id: documentation-file
      attributes:
          label: Documentation File
          description: Which documentation file needs improvement?
          options:
              - Overview (primary README.md)
              - Developer API Features
              - Quick Start
              - API Reference
              - Hooks Reference
              - JavaScript Integration
              - PHP Integration
              - External Plugin Integration
              - Advanced Usage
              - Troubleshooting
              - Example Plugins & Code Snippets
      validations:
          required: true

    - type: dropdown
      id: issue-type
      attributes:
          label: Type of Issue
          description: What kind of issue are you reporting?
          options:
              - Missing Information
              - Incorrect Information
              - Unclear Explanation
              - Outdated Content
              - Missing Examples
              - Poor Code Examples
              - Confusing Structure
              - Typos/Grammar
              - Needs More Detail
              - Other
      validations:
          required: true

    - type: textarea
      id: current-problem
      attributes:
          label: Current Problem
          description: What's unclear, missing, or incorrect?
          placeholder: Describe the issue...
      validations:
          required: true

    - type: textarea
      id: suggested-improvement
      attributes:
          label: Suggested Improvement
          description: How would you improve it?
          placeholder: Suggest changes, examples, or clarifications...
      validations:
          required: true

    - type: textarea
      id: use-case
      attributes:
          label: Use Case/Context (optional)
          description: Describe the situation where you encountered this documentation issue
          placeholder: What were you trying to accomplish?

    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context (optional)
          description: Any other relevant information or suggestions
