name: 🤝 Integration Help
description: Get help integrating Block Accessibility Checks with your custom blocks or plugin
title: '[Help]: '
labels: ['question', 'integration-help']
assignees: []
body:
    - type: markdown
      attributes:
          value: |
              Need help integrating Block Accessibility Checks with your project? Please provide as much detail as possible so I can give you the best assistance.

              **Note:** I will do my best to reply to your request, but response times may vary and I may not always be able to respond promptly.

    - type: checkboxes
      id: prerequisites
      attributes:
          label: Prerequisites
          description: Before requesting help, please confirm
          options:
              - label: I have read the developer documentation
                required: true
              - label: I have looked at the provided examples
                required: true
              - label: I have searched existing issues for similar questions
                required: true

    - type: dropdown
      id: help-type
      attributes:
          label: Type of Help Needed
          description: What kind of assistance are you looking for?
          options:
              - Getting Started - Basic integration setup
              - Custom Block Integration - Adding checks to existing blocks
              - New Block Development - Creating blocks with accessibility checks
              - Advanced Configuration - Complex validation rules
              - Troubleshooting - Something isn't working
              - Best Practices - How to implement correctly
              - Performance Optimization - Making integration efficient
              - Custom Validation Logic - Advanced JavaScript validation
              - Settings Integration - Admin panel configuration
              - Other
      validations:
          required: true

    - type: dropdown
      id: experience-level
      attributes:
          label: Experience Level
          description: How would you describe your WordPress development experience?
          options:
              - Beginner - New to WordPress/block development
              - Intermediate - Some WordPress development experience
              - Advanced - Experienced WordPress developer
              - Expert - Very experienced with WordPress/blocks
      validations:
          required: true

    - type: textarea
      id: project-description
      attributes:
          label: Project Description
          description: Describe your project and what you're trying to accomplish
          placeholder: |
              Tell us about:
              - What type of blocks or plugin you're working on
              - The accessibility checks you want to implement
              - Your end goals for the integration
      validations:
          required: true

    - type: textarea
      id: current-setup
      attributes:
          label: Current Setup
          description: Describe your current code setup and what you've already tried
          placeholder: |
              Include information about:
              - Your existing block structure
              - Any code you've already written
              - Integration steps you've completed
              - Your build process or development environment
      validations:
          required: true

    - type: textarea
      id: specific-question
      attributes:
          label: Specific Question or Issue
          description: What exactly are you stuck on or need help with?
          placeholder: |
              Be as specific as possible:
              - What specific error or behavior are you experiencing?
              - What functionality are you trying to implement?
              - Where exactly are you getting stuck?
      validations:
          required: true

    - type: textarea
      id: code-samples
      attributes:
          label: Relevant Code
          description: Share any relevant code you're working with
          placeholder: |
              Include:
              - Block registration code
              - Validation attempts
              - Error messages
              - Configuration files
          render: javascript

    - type: dropdown
      id: block-type
      attributes:
          label: Block Type
          description: What type of block are you working with?
          options:
              - Static Block (no dynamic content)
              - Dynamic Block (server-side rendering)
              - Block with Inner Blocks
              - Block with Custom Attributes
              - Block Pattern or Template
              - Multiple Block Types
              - Not sure

    - type: input
      id: block-name
      attributes:
          label: Block Name/Namespace
          description: What's your block's name or namespace?
          placeholder: 'e.g., my-plugin/custom-block, create-block/testimonial'

    - type: textarea
      id: desired-checks
      attributes:
          label: Desired Accessibility Checks
          description: What accessibility checks do you want to implement?
          placeholder: |
              Describe the validation rules you want to add:
              - Required fields or content
              - Format validations
              - WCAG compliance checks
              - User experience improvements
      validations:
          required: true

    - type: dropdown
      id: validation-timing
      attributes:
          label: Validation Timing
          description: When should your checks run?
          options:
              - Real-time (as user types)
              - On attribute change
              - Before publishing
              - On block selection
              - Not sure

    - type: dropdown
      id: error-handling
      attributes:
          label: Error Handling Preference
          description: How should validation errors be handled?
          options:
              - Block publishing (prevent save/publish)
              - Show warnings (allow save/publish)
              - Configurable in settings
              - Not sure

    - type: textarea
      id: attempted-solutions
      attributes:
          label: What Have You Tried?
          description: Describe any solutions or approaches you've already attempted
          placeholder: |
              Let us know:
              - Code approaches you've tried
              - Documentation sections you've followed
              - Examples you've attempted to modify
              - Any error messages you've encountered

    - type: textarea
      id: environment
      attributes:
          label: Development Environment
          description: Your development setup details
          value: |
              - **WordPress Version**: 
              - **PHP Version**: 
              - **Node.js Version**: 
              - **Build Tools**: (webpack, @wordpress/scripts, etc.)
              - **Local Environment**: (Local, XAMPP, Docker, etc.)
              - **Block Accessibility Checks Version**:
      validations:
          required: true

    # Urgency Level dropdown removed to avoid setting expectations

    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Any other information that might be helpful
          placeholder: |
              Include:
              - Links to similar functionality you're trying to achieve
              - Screenshots of desired behavior
              - Any constraints or requirements
              - Related plugins or tools you're using

    - type: checkboxes
      id: follow-up
      attributes:
          label: Follow-up Preferences
          description: How would you like to receive help?
          options:
              - label: I'm willing to share more code or details if needed
              - label: I can provide a test site or repository access if helpful
