import './styles.scss';
import './scripts/block-modifications/imageAttr';
import './scripts/registerPlugin';
import './scripts/block-validation/validationHooks';
import './scripts/block-checks/buttonValidation';
import './scripts/block-checks/headingRankGlobalListener';
import './scripts/block-checks/headingRankValidation';
import './scripts/block-checks/imageValidation';
import './scripts/block-checks/tableValidation';
