#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run the format command
npm run format

# Check if there are any changes in the working directory
if [ -n "$(git status --porcelain)" ]; then
  echo ""
  echo ""
  echo "\033[0;31mFormatting changes detected. Staging formatted files...\033[0m"
  echo ""
  
  # Stage the changes
  git add -u

  echo "\033[0;32mFormatted files have been staged. You can now commit your changes.\033[0m"
  echo ""
  # exit 1
fi

# If no changes, continue with the other tasks
npm run lint:js && npm run build
