name: Feature Request Label Automation
on:
  issues:
    types: [opened, labeled]

jobs:
  label-feature-category:
    if: contains(github.event.issue.labels.*.name, 'enhancement')
    runs-on: ubuntu-latest
    steps:
      - name: Extract feature category and add label
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body;
            const match = body.match(/### Feature Category\s*\n([^\n]+)/);
            if (match) {
              const category = match[1].trim();
              const labelMap = {
                "New Accessibility Check": "accessibility-check",
                "Block Type Support": "block-support",
                "Developer API Enhancement": "api-enhancement",
                "User Interface Improvement": "ui-improvement",
                "Settings/Configuration Option": "settings-config",
                "Performance Enhancement": "performance",
                "Integration Feature": "integration",
                "Other": "other"
              };
              const label = labelMap[category];
              if (label) {
                github.rest.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: [label]
                });
              }
            }
